### ISSUE TITLE
Monitoring free disk space

### ISSUE THREAD

**Issue by sashaoshurkov** [alfiosalanitri/server-guardian#2]
Hello Alfio,

Could you please add monitoring of free space in the section /

**Comment by alfiosalanitri** [comment]
Hi @sashaoshurkov, 
I will add this feature soon.

**Comment by sashaoshurkov** [comment]
> Hi @sashaoshurkov, I will add this feature soon.

Thank you, by the way I have already implemented it like this:
`# Get the storage usage value and if is greather then limit, send the message and exit
storage_usage=$(df / --output=pcent | tr -cd 0-9)
if [ "$storage_usage" -gt $storage_perc_limit ]; then
  message="High Storage usage: $storage_usage%"
  send_message "$message"
fi`

But I noticed one feature in your script: if there are several problems, for example, with RAM and with systemctl services, then only an error message with RAM will be sent to Telegram.

**Comment by alfiosalanitri** [comment]
I have implemented your code. Thanks.

Yes the script send an alert only for the first problem found. 
But in theory after this alert you should access the server and verify what's wrong

**Comment by sashaoshurkov** [comment]
Hello,
Wouldn't it be better to move the code on line 105 and write it after line 37 to keep the same style?
