### ISSUE TITLE
Systemctl failed services

### ISSUE THREAD

**Issue by babaz8** [alfiosalanitri/server-guardian#3]
Hi,
this is the only message I've managed to receive

`Server - debiangnulinux10: Systemctl failed services: ● systemd-modules-load.service loaded failed failed Load Kernel Modules vedi il file log nel server`

Thanks for your support in advance.

**Comment by alfiosalanitri** [comment]
Hi, the script send an alert when there are one or more failed services. 

The problem is the systemd-modules-load.service that fails to start. 

Try with `sudo systemctl restart systemd-modules-load.service` or [read here](https://superuser.com/a/1074637)
