### ISSUE TITLE
Wrong value in message "High CPU usage: %"

### ISSUE THREAD

**Issue by sashaoshurkov** [alfiosalanitri/server-guardian#6]
Hello,

Today I got a message like this "Server vdsina-srvr-35: `High CPU usage: 5%` see the log file on the server". But the calculation of the load in the code is not in percent. Is it possible to calculate the load as a percentage and send the percentage value to Telegram?

**Comment by alfiosalanitri** [comment]
Ok. 
Would do you like to fork this repo, to fix this bug or other improvements and then to create a merge request?

**Comment by sashaoshurkov** [comment]
Alfio,
Unfortunately I don't know how to fix this. The solution for calculating free disk space was suggested to me on the forum :)

**Comment by sashaoshurkov** [comment]
Thanks @alfiosalanitri
I've noticed that on some VDS the **/proc/cpuinfo** command does not work correctly. For example, instead of 4 cores, it shows 1.
root@vdsina-srvr-35:~# cat /proc/cpuinfo | grep 'cpu cores'
cpu cores	: 1
cpu cores	: 1
cpu cores	: 1
cpu cores	: 1

And on others it shows correctly.
root@sip-srvr-50:~# cat /proc/cpuinfo | grep 'cpu cores'
cpu cores	: 4
cpu cores	: 4
cpu cores	: 4
cpu cores	: 4

It may be better to use the **lscpu** command, it shows the correct value where cat /proc/cpuinfo fails?
root@vdsina-srvr-35:~# lscpu | grep '^CPU(s)'
CPU(s):  4

**Comment by alfiosalanitri** [comment]
Thanks for the feedback. I will fix this bug soon.

**Comment by sashaoshurkov** [comment]
Thank @alfiosalanitri 

I'm sorry to disturb you so often.

I would also like to know your opinion about load average, namely what value to monitor. I read the article https://scoutapm.com/blog/understanding-load-averages in which the author says that it is correct to monitor the value of 5 or 15 minutes, it makes no sense to monitor the value of 1 minute. Now I observe the following load average values: 4.16, 3.30, 3.21 (1min, 5min, 15min). Maybe it’s really worth monitoring the value of 5 minutes and receiving fewer messages in Telegram, especially as follows from the article, is this more correct?

**Comment by sashaoshurkov** [comment]
Thank you!

I think there is still a logical problem. The load_avg_last_minute variable is set to an integer. Therefore, with a load average of 1.4 (example for one core), the value of the variable load_avg_last_minute = 1 (100%). And even though we already have a load problem, we won't get notified because the _if [ $load_avg_percentage **-gt** 100 ]_ condition. Maybe replace **-gt** with **-ge** as an easy solution?

**Comment by alfiosalanitri** [comment]
> Thank you!
> 
> I think there is still a logical problem. The load_avg_last_minute variable is set to an integer. Therefore, with a load average of 1.4 (example for one core), the value of the variable load_avg_last_minute = 1 (100%). And even though we already have a load problem, we won't get notified because the _if [ $load_avg_percentage **-gt** 100 ]_ condition. Maybe replace **-gt** with **-ge** as an easy solution?

Hi, 
I have changed with -ge.
Also you can now control the script from cli with options. Read the readme file for more details.

Regards.
